cors:
  originPatterns: http://localhost:8080,http://localhost:3000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3080/bounty?useTimezone=true&serverTimezone=UTC
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
  springdoc:
    pathsToMatch:
      - /api/**/v1/**
      - /auth/**
    swagger-ui:
      use-root-path: true

